eureka:
  instance:
    non-secure-port: ${EXPOSED_PORT:server.port}
    preferIpAddress: true
    hostname: ${HOST_NAME:localhost}
    metadataMap.management.port: ${non-secure-port}
    health-check-url: ${hostname}:${non-secure-port}/actuator/health
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
