eureka:
  instance:
    non-secure-port: ${EXPOSED_PORT}
    preferIpAddress: true
    hostname: ${HOST_NAME}
    metadataMap.management.port: ${EXPOSED_PORT}
    health-check-url: ${HOST_NAME}:${EXPOSED_PORT}/actuator/health
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
